
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION IServiceSF_InsertUploadData_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_InsertUploadData_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_CheckLogin_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_CheckLogin_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_RegisterUser_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_RegisterUser_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadMapa_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadMapa_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_GetNumberOfUsers_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_GetNumberOfUsers_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_InsertTrack_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_InsertTrack_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_InfoMapa_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_InfoMapa_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadMusica_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadMusica_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadTextura_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadTextura_OutputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadModeloInimigo_InputMessage;
        WS_MESSAGE_DESCRIPTION IServiceSF_DownloadModeloInimigo_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // BasicHttpBinding_IServiceSF
        {
            struct  // BasicHttpBinding_IServiceSF_InsertUploadData
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_InsertUploadData;
            } BasicHttpBinding_IServiceSF_InsertUploadData;
            struct  // BasicHttpBinding_IServiceSF_CheckLogin
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_CheckLogin;
            } BasicHttpBinding_IServiceSF_CheckLogin;
            struct  // BasicHttpBinding_IServiceSF_RegisterUser
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_RegisterUser;
            } BasicHttpBinding_IServiceSF_RegisterUser;
            struct  // BasicHttpBinding_IServiceSF_DownloadMapa
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_DownloadMapa;
            } BasicHttpBinding_IServiceSF_DownloadMapa;
            struct  // BasicHttpBinding_IServiceSF_GetNumberOfUsers
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_GetNumberOfUsers;
            } BasicHttpBinding_IServiceSF_GetNumberOfUsers;
            struct  // BasicHttpBinding_IServiceSF_InsertTrack
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_InsertTrack;
            } BasicHttpBinding_IServiceSF_InsertTrack;
            struct  // BasicHttpBinding_IServiceSF_InfoMapa
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_InfoMapa;
            } BasicHttpBinding_IServiceSF_InfoMapa;
            struct  // BasicHttpBinding_IServiceSF_DownloadMusica
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_DownloadMusica;
            } BasicHttpBinding_IServiceSF_DownloadMusica;
            struct  // BasicHttpBinding_IServiceSF_DownloadTextura
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_DownloadTextura;
            } BasicHttpBinding_IServiceSF_DownloadTextura;
            struct  // BasicHttpBinding_IServiceSF_DownloadModeloInimigo
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IServiceSF_DownloadModeloInimigo;
            } BasicHttpBinding_IServiceSF_DownloadModeloInimigo;
            WS_OPERATION_DESCRIPTION* operations[10];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IServiceSF;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // BasicHttpBinding_IServiceSF
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IServiceSF;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING IServiceSF_InsertUploadData_InputMessageactionName;  // http://tempuri.org/IServiceSF/InsertUploadData
            WS_XML_STRING IServiceSF_InsertUploadData_OutputMessageactionName;  // http://tempuri.org/IServiceSF/InsertUploadDataResponse
            WS_XML_STRING IServiceSF_CheckLogin_InputMessageactionName;  // http://tempuri.org/IServiceSF/CheckLogin
            WS_XML_STRING IServiceSF_CheckLogin_OutputMessageactionName;  // http://tempuri.org/IServiceSF/CheckLoginResponse
            WS_XML_STRING IServiceSF_RegisterUser_InputMessageactionName;  // http://tempuri.org/IServiceSF/RegisterUser
            WS_XML_STRING IServiceSF_RegisterUser_OutputMessageactionName;  // http://tempuri.org/IServiceSF/RegisterUserResponse
            WS_XML_STRING IServiceSF_DownloadMapa_InputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadMapa
            WS_XML_STRING IServiceSF_DownloadMapa_OutputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadMapaResponse
            WS_XML_STRING IServiceSF_GetNumberOfUsers_InputMessageactionName;  // http://tempuri.org/IServiceSF/GetNumberOfUsers
            WS_XML_STRING IServiceSF_GetNumberOfUsers_OutputMessageactionName;  // http://tempuri.org/IServiceSF/GetNumberOfUsersResponse
            WS_XML_STRING IServiceSF_InsertTrack_InputMessageactionName;  // http://tempuri.org/IServiceSF/InsertTrack
            WS_XML_STRING IServiceSF_InsertTrack_OutputMessageactionName;  // http://tempuri.org/IServiceSF/InsertTrackResponse
            WS_XML_STRING IServiceSF_InfoMapa_InputMessageactionName;  // http://tempuri.org/IServiceSF/InfoMapa
            WS_XML_STRING IServiceSF_InfoMapa_OutputMessageactionName;  // http://tempuri.org/IServiceSF/InfoMapaResponse
            WS_XML_STRING IServiceSF_DownloadMusica_InputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadMusica
            WS_XML_STRING IServiceSF_DownloadMusica_OutputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadMusicaResponse
            WS_XML_STRING IServiceSF_DownloadTextura_InputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadTextura
            WS_XML_STRING IServiceSF_DownloadTextura_OutputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadTexturaResponse
            WS_XML_STRING IServiceSF_DownloadModeloInimigo_InputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadModeloInimigo
            WS_XML_STRING IServiceSF_DownloadModeloInimigo_OutputMessageactionName;  // http://tempuri.org/IServiceSF/DownloadModeloInimigoResponse
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct BasicHttpBinding_IServiceSF_InsertUploadDataParamStruct 
{
    WCHAR** user;
    int* score;
    WCHAR** mapa;
    BOOL* InsertUploadDataResult;
} BasicHttpBinding_IServiceSF_InsertUploadDataParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_InsertUploadDataOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_InsertUploadDataCallback _operation = (BasicHttpBinding_IServiceSF_InsertUploadDataCallback)_callback;
    BasicHttpBinding_IServiceSF_InsertUploadDataParamStruct *_stack =(BasicHttpBinding_IServiceSF_InsertUploadDataParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->user),
        *(_stack->score),
        *(_stack->mapa),
        (_stack->InsertUploadDataResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_CheckLoginParamStruct 
{
    WCHAR** user;
    WCHAR** password;
    BOOL* CheckLoginResult;
} BasicHttpBinding_IServiceSF_CheckLoginParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_CheckLoginOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_CheckLoginCallback _operation = (BasicHttpBinding_IServiceSF_CheckLoginCallback)_callback;
    BasicHttpBinding_IServiceSF_CheckLoginParamStruct *_stack =(BasicHttpBinding_IServiceSF_CheckLoginParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->user),
        *(_stack->password),
        (_stack->CheckLoginResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_RegisterUserParamStruct 
{
    WCHAR** user;
    WCHAR** password;
    BOOL* RegisterUserResult;
} BasicHttpBinding_IServiceSF_RegisterUserParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_RegisterUserOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_RegisterUserCallback _operation = (BasicHttpBinding_IServiceSF_RegisterUserCallback)_callback;
    BasicHttpBinding_IServiceSF_RegisterUserParamStruct *_stack =(BasicHttpBinding_IServiceSF_RegisterUserParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->user),
        *(_stack->password),
        (_stack->RegisterUserResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_DownloadMapaParamStruct 
{
    WCHAR** fileName;
    WCHAR** DownloadMapaResult;
} BasicHttpBinding_IServiceSF_DownloadMapaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_DownloadMapaOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_DownloadMapaCallback _operation = (BasicHttpBinding_IServiceSF_DownloadMapaCallback)_callback;
    BasicHttpBinding_IServiceSF_DownloadMapaParamStruct *_stack =(BasicHttpBinding_IServiceSF_DownloadMapaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->fileName),
        (_stack->DownloadMapaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_GetNumberOfUsersParamStruct 
{
    int* GetNumberOfUsersResult;
} BasicHttpBinding_IServiceSF_GetNumberOfUsersParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_GetNumberOfUsersOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_GetNumberOfUsersCallback _operation = (BasicHttpBinding_IServiceSF_GetNumberOfUsersCallback)_callback;
    BasicHttpBinding_IServiceSF_GetNumberOfUsersParamStruct *_stack =(BasicHttpBinding_IServiceSF_GetNumberOfUsersParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->GetNumberOfUsersResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_InsertTrackParamStruct 
{
    WCHAR** user;
    WCHAR** map;
    WCHAR** track;
    BOOL* InsertTrackResult;
} BasicHttpBinding_IServiceSF_InsertTrackParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_InsertTrackOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_InsertTrackCallback _operation = (BasicHttpBinding_IServiceSF_InsertTrackCallback)_callback;
    BasicHttpBinding_IServiceSF_InsertTrackParamStruct *_stack =(BasicHttpBinding_IServiceSF_InsertTrackParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->user),
        *(_stack->map),
        *(_stack->track),
        (_stack->InsertTrackResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_InfoMapaParamStruct 
{
    WCHAR** InfoMapaResult;
} BasicHttpBinding_IServiceSF_InfoMapaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_InfoMapaOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_InfoMapaCallback _operation = (BasicHttpBinding_IServiceSF_InfoMapaCallback)_callback;
    BasicHttpBinding_IServiceSF_InfoMapaParamStruct *_stack =(BasicHttpBinding_IServiceSF_InfoMapaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->InfoMapaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_DownloadMusicaParamStruct 
{
    WCHAR** nome;
    WCHAR** DownloadMusicaResult;
} BasicHttpBinding_IServiceSF_DownloadMusicaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_DownloadMusicaOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_DownloadMusicaCallback _operation = (BasicHttpBinding_IServiceSF_DownloadMusicaCallback)_callback;
    BasicHttpBinding_IServiceSF_DownloadMusicaParamStruct *_stack =(BasicHttpBinding_IServiceSF_DownloadMusicaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->nome),
        (_stack->DownloadMusicaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_DownloadTexturaParamStruct 
{
    WCHAR** nome;
    WCHAR** DownloadTexturaResult;
} BasicHttpBinding_IServiceSF_DownloadTexturaParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_DownloadTexturaOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_DownloadTexturaCallback _operation = (BasicHttpBinding_IServiceSF_DownloadTexturaCallback)_callback;
    BasicHttpBinding_IServiceSF_DownloadTexturaParamStruct *_stack =(BasicHttpBinding_IServiceSF_DownloadTexturaParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->nome),
        (_stack->DownloadTexturaResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IServiceSF_DownloadModeloInimigoParamStruct 
{
    WCHAR** nome;
    WCHAR** DownloadModeloInimigoResult;
} BasicHttpBinding_IServiceSF_DownloadModeloInimigoParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IServiceSF_DownloadModeloInimigoOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IServiceSF_DownloadModeloInimigoCallback _operation = (BasicHttpBinding_IServiceSF_DownloadModeloInimigoCallback)_callback;
    BasicHttpBinding_IServiceSF_DownloadModeloInimigoParamStruct *_stack =(BasicHttpBinding_IServiceSF_DownloadModeloInimigoParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->nome),
        (_stack->DownloadModeloInimigoResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    {  // messages
        {  // message description for IServiceSF_InsertUploadData_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertUploadData_InputMessageactionName, // http://tempuri.org/IServiceSF/InsertUploadData
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertUploadData, 
        },    // message description for IServiceSF_InsertUploadData_InputMessage
        {  // message description for IServiceSF_InsertUploadData_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertUploadData_OutputMessageactionName, // http://tempuri.org/IServiceSF/InsertUploadDataResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertUploadDataResponse, 
        },    // message description for IServiceSF_InsertUploadData_OutputMessage
        {  // message description for IServiceSF_CheckLogin_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_CheckLogin_InputMessageactionName, // http://tempuri.org/IServiceSF/CheckLogin
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.CheckLogin, 
        },    // message description for IServiceSF_CheckLogin_InputMessage
        {  // message description for IServiceSF_CheckLogin_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_CheckLogin_OutputMessageactionName, // http://tempuri.org/IServiceSF/CheckLoginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.CheckLoginResponse, 
        },    // message description for IServiceSF_CheckLogin_OutputMessage
        {  // message description for IServiceSF_RegisterUser_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_RegisterUser_InputMessageactionName, // http://tempuri.org/IServiceSF/RegisterUser
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.RegisterUser, 
        },    // message description for IServiceSF_RegisterUser_InputMessage
        {  // message description for IServiceSF_RegisterUser_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_RegisterUser_OutputMessageactionName, // http://tempuri.org/IServiceSF/RegisterUserResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.RegisterUserResponse, 
        },    // message description for IServiceSF_RegisterUser_OutputMessage
        {  // message description for IServiceSF_DownloadMapa_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMapa_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMapa
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMapa, 
        },    // message description for IServiceSF_DownloadMapa_InputMessage
        {  // message description for IServiceSF_DownloadMapa_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMapa_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMapaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMapaResponse, 
        },    // message description for IServiceSF_DownloadMapa_OutputMessage
        {  // message description for IServiceSF_GetNumberOfUsers_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_GetNumberOfUsers_InputMessageactionName, // http://tempuri.org/IServiceSF/GetNumberOfUsers
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetNumberOfUsers, 
        },    // message description for IServiceSF_GetNumberOfUsers_InputMessage
        {  // message description for IServiceSF_GetNumberOfUsers_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_GetNumberOfUsers_OutputMessageactionName, // http://tempuri.org/IServiceSF/GetNumberOfUsersResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetNumberOfUsersResponse, 
        },    // message description for IServiceSF_GetNumberOfUsers_OutputMessage
        {  // message description for IServiceSF_InsertTrack_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertTrack_InputMessageactionName, // http://tempuri.org/IServiceSF/InsertTrack
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertTrack, 
        },    // message description for IServiceSF_InsertTrack_InputMessage
        {  // message description for IServiceSF_InsertTrack_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertTrack_OutputMessageactionName, // http://tempuri.org/IServiceSF/InsertTrackResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertTrackResponse, 
        },    // message description for IServiceSF_InsertTrack_OutputMessage
        {  // message description for IServiceSF_InfoMapa_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InfoMapa_InputMessageactionName, // http://tempuri.org/IServiceSF/InfoMapa
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InfoMapa, 
        },    // message description for IServiceSF_InfoMapa_InputMessage
        {  // message description for IServiceSF_InfoMapa_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InfoMapa_OutputMessageactionName, // http://tempuri.org/IServiceSF/InfoMapaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InfoMapaResponse, 
        },    // message description for IServiceSF_InfoMapa_OutputMessage
        {  // message description for IServiceSF_DownloadMusica_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMusica_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMusica
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMusica, 
        },    // message description for IServiceSF_DownloadMusica_InputMessage
        {  // message description for IServiceSF_DownloadMusica_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMusica_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMusicaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMusicaResponse, 
        },    // message description for IServiceSF_DownloadMusica_OutputMessage
        {  // message description for IServiceSF_DownloadTextura_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadTextura_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadTextura
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadTextura, 
        },    // message description for IServiceSF_DownloadTextura_InputMessage
        {  // message description for IServiceSF_DownloadTextura_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadTextura_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadTexturaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadTexturaResponse, 
        },    // message description for IServiceSF_DownloadTextura_OutputMessage
        {  // message description for IServiceSF_DownloadModeloInimigo_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadModeloInimigo_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadModeloInimigo
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadModeloInimigo, 
        },    // message description for IServiceSF_DownloadModeloInimigo_InputMessage
        {  // message description for IServiceSF_DownloadModeloInimigo_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadModeloInimigo_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadModeloInimigoResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadModeloInimigoResponse, 
        },    // message description for IServiceSF_DownloadModeloInimigo_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // BasicHttpBinding_IServiceSF,
            {  // BasicHttpBinding_IServiceSF_InsertUploadData
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_InsertUploadData
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_InsertUploadData
                {  // operation description for BasicHttpBinding_IServiceSF_InsertUploadData
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_InsertUploadData_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_InsertUploadData_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InsertUploadData.params,
                    BasicHttpBinding_IServiceSF_InsertUploadDataOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_InsertUploadData
            },  // BasicHttpBinding_IServiceSF_InsertUploadData
            {  // BasicHttpBinding_IServiceSF_CheckLogin
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_CheckLogin
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_CheckLogin
                {  // operation description for BasicHttpBinding_IServiceSF_CheckLogin
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_CheckLogin_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_CheckLogin_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_CheckLogin.params,
                    BasicHttpBinding_IServiceSF_CheckLoginOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_CheckLogin
            },  // BasicHttpBinding_IServiceSF_CheckLogin
            {  // BasicHttpBinding_IServiceSF_RegisterUser
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_RegisterUser
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_RegisterUser
                {  // operation description for BasicHttpBinding_IServiceSF_RegisterUser
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_RegisterUser_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_RegisterUser_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_RegisterUser.params,
                    BasicHttpBinding_IServiceSF_RegisterUserOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_RegisterUser
            },  // BasicHttpBinding_IServiceSF_RegisterUser
            {  // BasicHttpBinding_IServiceSF_DownloadMapa
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadMapa
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadMapa
                {  // operation description for BasicHttpBinding_IServiceSF_DownloadMapa
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadMapa_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadMapa_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadMapa.params,
                    BasicHttpBinding_IServiceSF_DownloadMapaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_DownloadMapa
            },  // BasicHttpBinding_IServiceSF_DownloadMapa
            {  // BasicHttpBinding_IServiceSF_GetNumberOfUsers
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_GetNumberOfUsers
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_GetNumberOfUsers
                {  // operation description for BasicHttpBinding_IServiceSF_GetNumberOfUsers
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_GetNumberOfUsers_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_GetNumberOfUsers_OutputMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_GetNumberOfUsers.params,
                    BasicHttpBinding_IServiceSF_GetNumberOfUsersOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_GetNumberOfUsers
            },  // BasicHttpBinding_IServiceSF_GetNumberOfUsers
            {  // BasicHttpBinding_IServiceSF_InsertTrack
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_InsertTrack
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_InsertTrack
                {  // operation description for BasicHttpBinding_IServiceSF_InsertTrack
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_InsertTrack_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_InsertTrack_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InsertTrack.params,
                    BasicHttpBinding_IServiceSF_InsertTrackOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_InsertTrack
            },  // BasicHttpBinding_IServiceSF_InsertTrack
            {  // BasicHttpBinding_IServiceSF_InfoMapa
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_InfoMapa
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_InfoMapa
                {  // operation description for BasicHttpBinding_IServiceSF_InfoMapa
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_InfoMapa_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_InfoMapa_OutputMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InfoMapa.params,
                    BasicHttpBinding_IServiceSF_InfoMapaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_InfoMapa
            },  // BasicHttpBinding_IServiceSF_InfoMapa
            {  // BasicHttpBinding_IServiceSF_DownloadMusica
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadMusica
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadMusica
                {  // operation description for BasicHttpBinding_IServiceSF_DownloadMusica
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadMusica_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadMusica_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadMusica.params,
                    BasicHttpBinding_IServiceSF_DownloadMusicaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_DownloadMusica
            },  // BasicHttpBinding_IServiceSF_DownloadMusica
            {  // BasicHttpBinding_IServiceSF_DownloadTextura
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadTextura
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadTextura
                {  // operation description for BasicHttpBinding_IServiceSF_DownloadTextura
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadTextura_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadTextura_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadTextura.params,
                    BasicHttpBinding_IServiceSF_DownloadTexturaOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_DownloadTextura
            },  // BasicHttpBinding_IServiceSF_DownloadTextura
            {  // BasicHttpBinding_IServiceSF_DownloadModeloInimigo
                {  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadModeloInimigo
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IServiceSF_DownloadModeloInimigo
                {  // operation description for BasicHttpBinding_IServiceSF_DownloadModeloInimigo
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadModeloInimigo_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IServiceSF_DownloadModeloInimigo_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadModeloInimigo.params,
                    BasicHttpBinding_IServiceSF_DownloadModeloInimigoOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IServiceSF_DownloadModeloInimigo
            },  // BasicHttpBinding_IServiceSF_DownloadModeloInimigo
            {  // array of operations for BasicHttpBinding_IServiceSF
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InsertUploadData.BasicHttpBinding_IServiceSF_InsertUploadData,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_CheckLogin.BasicHttpBinding_IServiceSF_CheckLogin,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_RegisterUser.BasicHttpBinding_IServiceSF_RegisterUser,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadMapa.BasicHttpBinding_IServiceSF_DownloadMapa,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_GetNumberOfUsers.BasicHttpBinding_IServiceSF_GetNumberOfUsers,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InsertTrack.BasicHttpBinding_IServiceSF_InsertTrack,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InfoMapa.BasicHttpBinding_IServiceSF_InfoMapa,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadMusica.BasicHttpBinding_IServiceSF_DownloadMusica,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadTextura.BasicHttpBinding_IServiceSF_DownloadTextura,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadModeloInimigo.BasicHttpBinding_IServiceSF_DownloadModeloInimigo,
            },  // array of operations for BasicHttpBinding_IServiceSF
            {  // contract description for BasicHttpBinding_IServiceSF
            10,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.operations,
            },  // end of contract description for BasicHttpBinding_IServiceSF
        },  // BasicHttpBinding_IServiceSF
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IServiceSF,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/InsertUploadData",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/InsertUploadDataResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/CheckLogin",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/CheckLoginResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/RegisterUser",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/RegisterUserResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadMapa",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadMapaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/GetNumberOfUsers",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/GetNumberOfUsersResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/InsertTrack",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/InsertTrackResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/InfoMapa",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/InfoMapaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadMusica",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadMusicaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadTextura",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadTexturaResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadModeloInimigo",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IServiceSF/DownloadModeloInimigoResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 19),
        },  // end of xmlStrings
        
        {  // tempuri_org_wsdldictionary
          // 8e29781e-e515-41e1-8e4f-a70d91275c95 
        { 0x8e29781e, 0xe515, 0x41e1, { 0x8e, 0x4f, 0xa7,0x0d, 0x91, 0x27, 0x5c, 0x95 } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        20,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: BasicHttpBinding_IServiceSF_InsertUploadData
HRESULT WINAPI BasicHttpBinding_IServiceSF_InsertUploadData(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* user, 
    _In_ int score, 
    _In_opt_z_ WCHAR* mapa, 
    _Out_ BOOL* InsertUploadDataResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &user;
    _argList[1] = &score;
    _argList[2] = &mapa;
    _argList[3] = &InsertUploadDataResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InsertUploadData.BasicHttpBinding_IServiceSF_InsertUploadData,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_CheckLogin
HRESULT WINAPI BasicHttpBinding_IServiceSF_CheckLogin(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* password, 
    _Out_ BOOL* CheckLoginResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &user;
    _argList[1] = &password;
    _argList[2] = &CheckLoginResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_CheckLogin.BasicHttpBinding_IServiceSF_CheckLogin,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_RegisterUser
HRESULT WINAPI BasicHttpBinding_IServiceSF_RegisterUser(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* password, 
    _Out_ BOOL* RegisterUserResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &user;
    _argList[1] = &password;
    _argList[2] = &RegisterUserResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_RegisterUser.BasicHttpBinding_IServiceSF_RegisterUser,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_DownloadMapa
HRESULT WINAPI BasicHttpBinding_IServiceSF_DownloadMapa(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* fileName, 
    _Outptr_opt_result_z_ WCHAR** DownloadMapaResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &fileName;
    _argList[1] = &DownloadMapaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadMapa.BasicHttpBinding_IServiceSF_DownloadMapa,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_GetNumberOfUsers
HRESULT WINAPI BasicHttpBinding_IServiceSF_GetNumberOfUsers(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ int* GetNumberOfUsersResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[1]; 
    _argList[0] = &GetNumberOfUsersResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_GetNumberOfUsers.BasicHttpBinding_IServiceSF_GetNumberOfUsers,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_InsertTrack
HRESULT WINAPI BasicHttpBinding_IServiceSF_InsertTrack(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* map, 
    _In_opt_z_ WCHAR* track, 
    _Out_ BOOL* InsertTrackResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &user;
    _argList[1] = &map;
    _argList[2] = &track;
    _argList[3] = &InsertTrackResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InsertTrack.BasicHttpBinding_IServiceSF_InsertTrack,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_InfoMapa
HRESULT WINAPI BasicHttpBinding_IServiceSF_InfoMapa(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Outptr_opt_result_z_ WCHAR** InfoMapaResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[1]; 
    _argList[0] = &InfoMapaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_InfoMapa.BasicHttpBinding_IServiceSF_InfoMapa,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_DownloadMusica
HRESULT WINAPI BasicHttpBinding_IServiceSF_DownloadMusica(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* nome, 
    _Outptr_opt_result_z_ WCHAR** DownloadMusicaResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &nome;
    _argList[1] = &DownloadMusicaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadMusica.BasicHttpBinding_IServiceSF_DownloadMusica,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_DownloadTextura
HRESULT WINAPI BasicHttpBinding_IServiceSF_DownloadTextura(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* nome, 
    _Outptr_opt_result_z_ WCHAR** DownloadTexturaResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &nome;
    _argList[1] = &DownloadTexturaResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadTextura.BasicHttpBinding_IServiceSF_DownloadTextura,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IServiceSF_DownloadModeloInimigo
HRESULT WINAPI BasicHttpBinding_IServiceSF_DownloadModeloInimigo(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* nome, 
    _Outptr_opt_result_z_ WCHAR** DownloadModeloInimigoResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &nome;
    _argList[1] = &DownloadModeloInimigoResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.BasicHttpBinding_IServiceSF_DownloadModeloInimigo.BasicHttpBinding_IServiceSF_DownloadModeloInimigo,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {  // messages
        {  // message description for IServiceSF_InsertUploadData_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertUploadData_InputMessageactionName, // http://tempuri.org/IServiceSF/InsertUploadData
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertUploadData, 
        },    // message description for IServiceSF_InsertUploadData_InputMessage
        {  // message description for IServiceSF_InsertUploadData_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertUploadData_OutputMessageactionName, // http://tempuri.org/IServiceSF/InsertUploadDataResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertUploadDataResponse, 
        },    // message description for IServiceSF_InsertUploadData_OutputMessage
        {  // message description for IServiceSF_CheckLogin_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_CheckLogin_InputMessageactionName, // http://tempuri.org/IServiceSF/CheckLogin
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.CheckLogin, 
        },    // message description for IServiceSF_CheckLogin_InputMessage
        {  // message description for IServiceSF_CheckLogin_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_CheckLogin_OutputMessageactionName, // http://tempuri.org/IServiceSF/CheckLoginResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.CheckLoginResponse, 
        },    // message description for IServiceSF_CheckLogin_OutputMessage
        {  // message description for IServiceSF_RegisterUser_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_RegisterUser_InputMessageactionName, // http://tempuri.org/IServiceSF/RegisterUser
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.RegisterUser, 
        },    // message description for IServiceSF_RegisterUser_InputMessage
        {  // message description for IServiceSF_RegisterUser_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_RegisterUser_OutputMessageactionName, // http://tempuri.org/IServiceSF/RegisterUserResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.RegisterUserResponse, 
        },    // message description for IServiceSF_RegisterUser_OutputMessage
        {  // message description for IServiceSF_DownloadMapa_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMapa_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMapa
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMapa, 
        },    // message description for IServiceSF_DownloadMapa_InputMessage
        {  // message description for IServiceSF_DownloadMapa_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMapa_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMapaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMapaResponse, 
        },    // message description for IServiceSF_DownloadMapa_OutputMessage
        {  // message description for IServiceSF_GetNumberOfUsers_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_GetNumberOfUsers_InputMessageactionName, // http://tempuri.org/IServiceSF/GetNumberOfUsers
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetNumberOfUsers, 
        },    // message description for IServiceSF_GetNumberOfUsers_InputMessage
        {  // message description for IServiceSF_GetNumberOfUsers_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_GetNumberOfUsers_OutputMessageactionName, // http://tempuri.org/IServiceSF/GetNumberOfUsersResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetNumberOfUsersResponse, 
        },    // message description for IServiceSF_GetNumberOfUsers_OutputMessage
        {  // message description for IServiceSF_InsertTrack_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertTrack_InputMessageactionName, // http://tempuri.org/IServiceSF/InsertTrack
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertTrack, 
        },    // message description for IServiceSF_InsertTrack_InputMessage
        {  // message description for IServiceSF_InsertTrack_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InsertTrack_OutputMessageactionName, // http://tempuri.org/IServiceSF/InsertTrackResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InsertTrackResponse, 
        },    // message description for IServiceSF_InsertTrack_OutputMessage
        {  // message description for IServiceSF_InfoMapa_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InfoMapa_InputMessageactionName, // http://tempuri.org/IServiceSF/InfoMapa
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InfoMapa, 
        },    // message description for IServiceSF_InfoMapa_InputMessage
        {  // message description for IServiceSF_InfoMapa_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_InfoMapa_OutputMessageactionName, // http://tempuri.org/IServiceSF/InfoMapaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.InfoMapaResponse, 
        },    // message description for IServiceSF_InfoMapa_OutputMessage
        {  // message description for IServiceSF_DownloadMusica_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMusica_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMusica
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMusica, 
        },    // message description for IServiceSF_DownloadMusica_InputMessage
        {  // message description for IServiceSF_DownloadMusica_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadMusica_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadMusicaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadMusicaResponse, 
        },    // message description for IServiceSF_DownloadMusica_OutputMessage
        {  // message description for IServiceSF_DownloadTextura_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadTextura_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadTextura
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadTextura, 
        },    // message description for IServiceSF_DownloadTextura_InputMessage
        {  // message description for IServiceSF_DownloadTextura_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadTextura_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadTexturaResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadTexturaResponse, 
        },    // message description for IServiceSF_DownloadTextura_OutputMessage
        {  // message description for IServiceSF_DownloadModeloInimigo_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadModeloInimigo_InputMessageactionName, // http://tempuri.org/IServiceSF/DownloadModeloInimigo
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadModeloInimigo, 
        },    // message description for IServiceSF_DownloadModeloInimigo_InputMessage
        {  // message description for IServiceSF_DownloadModeloInimigo_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IServiceSF_DownloadModeloInimigo_OutputMessageactionName, // http://tempuri.org/IServiceSF/DownloadModeloInimigoResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.DownloadModeloInimigoResponse, 
        },    // message description for IServiceSF_DownloadModeloInimigo_OutputMessage
    },  // messages
    {  // contracts
        {  // BasicHttpBinding_IServiceSF
            10,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IServiceSF.operations,
        },  // end of BasicHttpBinding_IServiceSF
    },  // contracts
    {  // policies
        {  // template description for BasicHttpBinding_IServiceSF
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IServiceSF.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IServiceSF_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IServiceSF,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IServiceSF),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IServiceSF_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct BasicHttpBinding_IServiceSFFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IServiceSF;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IServiceSF,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IServiceSF),
        serviceEndpoint,
        error);
}
