
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _InsertUploadData
        {
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION score;
            WS_FIELD_DESCRIPTION mapa;
            WS_FIELD_DESCRIPTION* _InsertUploadDataFields [3]; 
        } _InsertUploadDatadescs; // end of _InsertUploadData
        struct  // _InsertUploadDataResponse
        {
            WS_FIELD_DESCRIPTION InsertUploadDataResult;
            WS_FIELD_DESCRIPTION* _InsertUploadDataResponseFields [1]; 
        } _InsertUploadDataResponsedescs; // end of _InsertUploadDataResponse
        struct  // _CheckLogin
        {
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION password;
            WS_FIELD_DESCRIPTION* _CheckLoginFields [2]; 
        } _CheckLogindescs; // end of _CheckLogin
        struct  // _CheckLoginResponse
        {
            WS_FIELD_DESCRIPTION CheckLoginResult;
            WS_FIELD_DESCRIPTION* _CheckLoginResponseFields [1]; 
        } _CheckLoginResponsedescs; // end of _CheckLoginResponse
        struct  // _RegisterUser
        {
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION password;
            WS_FIELD_DESCRIPTION* _RegisterUserFields [2]; 
        } _RegisterUserdescs; // end of _RegisterUser
        struct  // _RegisterUserResponse
        {
            WS_FIELD_DESCRIPTION RegisterUserResult;
            WS_FIELD_DESCRIPTION* _RegisterUserResponseFields [1]; 
        } _RegisterUserResponsedescs; // end of _RegisterUserResponse
        struct  // _DownloadMapa
        {
            WS_FIELD_DESCRIPTION fileName;
            WS_FIELD_DESCRIPTION* _DownloadMapaFields [1]; 
        } _DownloadMapadescs; // end of _DownloadMapa
        struct  // _DownloadMapaResponse
        {
            WS_FIELD_DESCRIPTION DownloadMapaResult;
            WS_FIELD_DESCRIPTION* _DownloadMapaResponseFields [1]; 
        } _DownloadMapaResponsedescs; // end of _DownloadMapaResponse
        struct  // _GetNumberOfUsersResponse
        {
            WS_FIELD_DESCRIPTION GetNumberOfUsersResult;
            WS_FIELD_DESCRIPTION* _GetNumberOfUsersResponseFields [1]; 
        } _GetNumberOfUsersResponsedescs; // end of _GetNumberOfUsersResponse
        struct  // _InsertTrack
        {
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION map;
            WS_FIELD_DESCRIPTION track;
            WS_FIELD_DESCRIPTION* _InsertTrackFields [3]; 
        } _InsertTrackdescs; // end of _InsertTrack
        struct  // _InsertTrackResponse
        {
            WS_FIELD_DESCRIPTION InsertTrackResult;
            WS_FIELD_DESCRIPTION* _InsertTrackResponseFields [1]; 
        } _InsertTrackResponsedescs; // end of _InsertTrackResponse
        struct  // _InfoMapaResponse
        {
            WS_FIELD_DESCRIPTION InfoMapaResult;
            WS_FIELD_DESCRIPTION* _InfoMapaResponseFields [1]; 
        } _InfoMapaResponsedescs; // end of _InfoMapaResponse
        struct  // _DownloadMusica
        {
            WS_FIELD_DESCRIPTION nome;
            WS_FIELD_DESCRIPTION* _DownloadMusicaFields [1]; 
        } _DownloadMusicadescs; // end of _DownloadMusica
        struct  // _DownloadMusicaResponse
        {
            WS_FIELD_DESCRIPTION DownloadMusicaResult;
            WS_FIELD_DESCRIPTION* _DownloadMusicaResponseFields [1]; 
        } _DownloadMusicaResponsedescs; // end of _DownloadMusicaResponse
        struct  // _DownloadTextura
        {
            WS_FIELD_DESCRIPTION nome;
            WS_FIELD_DESCRIPTION* _DownloadTexturaFields [1]; 
        } _DownloadTexturadescs; // end of _DownloadTextura
        struct  // _DownloadTexturaResponse
        {
            WS_FIELD_DESCRIPTION DownloadTexturaResult;
            WS_FIELD_DESCRIPTION* _DownloadTexturaResponseFields [1]; 
        } _DownloadTexturaResponsedescs; // end of _DownloadTexturaResponse
        struct  // _DownloadModeloInimigo
        {
            WS_FIELD_DESCRIPTION nome;
            WS_FIELD_DESCRIPTION* _DownloadModeloInimigoFields [1]; 
        } _DownloadModeloInimigodescs; // end of _DownloadModeloInimigo
        struct  // _DownloadModeloInimigoResponse
        {
            WS_FIELD_DESCRIPTION DownloadModeloInimigoResult;
            WS_FIELD_DESCRIPTION* _DownloadModeloInimigoResponseFields [1]; 
        } _DownloadModeloInimigoResponsedescs; // end of _DownloadModeloInimigoResponse
    } globalElements;  // end of global elements
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _InsertUploadDataTypeName;  // InsertUploadData
            WS_XML_STRING _InsertUploadDataTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _InsertUploadDatauserLocalName;  // user
            WS_XML_STRING _InsertUploadDatascoreLocalName;  // score
            WS_XML_STRING _InsertUploadDatamapaLocalName;  // mapa
            WS_XML_STRING _InsertUploadDataResponseTypeName;  // InsertUploadDataResponse
            WS_XML_STRING _InsertUploadDataResponseInsertUploadDataResultLocalName;  // InsertUploadDataResult
            WS_XML_STRING _CheckLoginTypeName;  // CheckLogin
            WS_XML_STRING _CheckLoginpasswordLocalName;  // password
            WS_XML_STRING _CheckLoginResponseTypeName;  // CheckLoginResponse
            WS_XML_STRING _CheckLoginResponseCheckLoginResultLocalName;  // CheckLoginResult
            WS_XML_STRING _RegisterUserTypeName;  // RegisterUser
            WS_XML_STRING _RegisterUserResponseTypeName;  // RegisterUserResponse
            WS_XML_STRING _RegisterUserResponseRegisterUserResultLocalName;  // RegisterUserResult
            WS_XML_STRING _DownloadMapaTypeName;  // DownloadMapa
            WS_XML_STRING _DownloadMapafileNameLocalName;  // fileName
            WS_XML_STRING _DownloadMapaResponseTypeName;  // DownloadMapaResponse
            WS_XML_STRING _DownloadMapaResponseDownloadMapaResultLocalName;  // DownloadMapaResult
            WS_XML_STRING _GetNumberOfUsersTypeName;  // GetNumberOfUsers
            WS_XML_STRING _GetNumberOfUsersResponseTypeName;  // GetNumberOfUsersResponse
            WS_XML_STRING _GetNumberOfUsersResponseGetNumberOfUsersResultLocalName;  // GetNumberOfUsersResult
            WS_XML_STRING _InsertTrackTypeName;  // InsertTrack
            WS_XML_STRING _InsertTrackmapLocalName;  // map
            WS_XML_STRING _InsertTracktrackLocalName;  // track
            WS_XML_STRING _InsertTrackResponseTypeName;  // InsertTrackResponse
            WS_XML_STRING _InsertTrackResponseInsertTrackResultLocalName;  // InsertTrackResult
            WS_XML_STRING _InfoMapaTypeName;  // InfoMapa
            WS_XML_STRING _InfoMapaResponseTypeName;  // InfoMapaResponse
            WS_XML_STRING _InfoMapaResponseInfoMapaResultLocalName;  // InfoMapaResult
            WS_XML_STRING _DownloadMusicaTypeName;  // DownloadMusica
            WS_XML_STRING _DownloadMusicanomeLocalName;  // nome
            WS_XML_STRING _DownloadMusicaResponseTypeName;  // DownloadMusicaResponse
            WS_XML_STRING _DownloadMusicaResponseDownloadMusicaResultLocalName;  // DownloadMusicaResult
            WS_XML_STRING _DownloadTexturaTypeName;  // DownloadTextura
            WS_XML_STRING _DownloadTexturaResponseTypeName;  // DownloadTexturaResponse
            WS_XML_STRING _DownloadTexturaResponseDownloadTexturaResultLocalName;  // DownloadTexturaResult
            WS_XML_STRING _DownloadModeloInimigoTypeName;  // DownloadModeloInimigo
            WS_XML_STRING _DownloadModeloInimigoResponseTypeName;  // DownloadModeloInimigoResponse
            WS_XML_STRING _DownloadModeloInimigoResponseDownloadModeloInimigoResultLocalName;  // DownloadModeloInimigoResult
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {  // _InsertUploadData
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDatauserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_InsertUploadData, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for score
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDatascoreLocalName, // score
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_InsertUploadData, score),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for score
            {  // field description for mapa
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDatamapaLocalName, // mapa
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_InsertUploadData, mapa),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for mapa
            {  // fields description for _InsertUploadData
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDatadescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDatadescs.score,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDatadescs.mapa,
            },
        },    // _InsertUploadData
        {  // _InsertUploadDataResponse
            {  // field description for InsertUploadDataResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataResponseInsertUploadDataResultLocalName, // InsertUploadDataResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_InsertUploadDataResponse, InsertUploadDataResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for InsertUploadDataResult
            {  // fields description for _InsertUploadDataResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDataResponsedescs.InsertUploadDataResult,
            },
        },    // _InsertUploadDataResponse
        {  // _CheckLogin
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDatauserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_CheckLogin, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for password
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginpasswordLocalName, // password
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_CheckLogin, password),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for password
            {  // fields description for _CheckLogin
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._CheckLogindescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._CheckLogindescs.password,
            },
        },    // _CheckLogin
        {  // _CheckLoginResponse
            {  // field description for CheckLoginResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginResponseCheckLoginResultLocalName, // CheckLoginResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_CheckLoginResponse, CheckLoginResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for CheckLoginResult
            {  // fields description for _CheckLoginResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._CheckLoginResponsedescs.CheckLoginResult,
            },
        },    // _CheckLoginResponse
        {  // _RegisterUser
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDatauserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_RegisterUser, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for password
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginpasswordLocalName, // password
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_RegisterUser, password),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for password
            {  // fields description for _RegisterUser
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserdescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserdescs.password,
            },
        },    // _RegisterUser
        {  // _RegisterUserResponse
            {  // field description for RegisterUserResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._RegisterUserResponseRegisterUserResultLocalName, // RegisterUserResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_RegisterUserResponse, RegisterUserResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for RegisterUserResult
            {  // fields description for _RegisterUserResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserResponsedescs.RegisterUserResult,
            },
        },    // _RegisterUserResponse
        {  // _DownloadMapa
            {  // field description for fileName
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMapafileNameLocalName, // fileName
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadMapa, fileName),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for fileName
            {  // fields description for _DownloadMapa
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMapadescs.fileName,
            },
        },    // _DownloadMapa
        {  // _DownloadMapaResponse
            {  // field description for DownloadMapaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMapaResponseDownloadMapaResultLocalName, // DownloadMapaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadMapaResponse, DownloadMapaResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for DownloadMapaResult
            {  // fields description for _DownloadMapaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMapaResponsedescs.DownloadMapaResult,
            },
        },    // _DownloadMapaResponse
        {  // _GetNumberOfUsersResponse
            {  // field description for GetNumberOfUsersResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetNumberOfUsersResponseGetNumberOfUsersResultLocalName, // GetNumberOfUsersResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetNumberOfUsersResponse, GetNumberOfUsersResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for GetNumberOfUsersResult
            {  // fields description for _GetNumberOfUsersResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetNumberOfUsersResponsedescs.GetNumberOfUsersResult,
            },
        },    // _GetNumberOfUsersResponse
        {  // _InsertTrack
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDatauserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_InsertTrack, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for map
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTrackmapLocalName, // map
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_InsertTrack, map),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for map
            {  // field description for track
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTracktrackLocalName, // track
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_InsertTrack, track),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for track
            {  // fields description for _InsertTrack
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackdescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackdescs.map,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackdescs.track,
            },
        },    // _InsertTrack
        {  // _InsertTrackResponse
            {  // field description for InsertTrackResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTrackResponseInsertTrackResultLocalName, // InsertTrackResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(_InsertTrackResponse, InsertTrackResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for InsertTrackResult
            {  // fields description for _InsertTrackResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackResponsedescs.InsertTrackResult,
            },
        },    // _InsertTrackResponse
        {  // _InfoMapaResponse
            {  // field description for InfoMapaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InfoMapaResponseInfoMapaResultLocalName, // InfoMapaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_InfoMapaResponse, InfoMapaResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for InfoMapaResult
            {  // fields description for _InfoMapaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._InfoMapaResponsedescs.InfoMapaResult,
            },
        },    // _InfoMapaResponse
        {  // _DownloadMusica
            {  // field description for nome
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicanomeLocalName, // nome
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadMusica, nome),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for nome
            {  // fields description for _DownloadMusica
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMusicadescs.nome,
            },
        },    // _DownloadMusica
        {  // _DownloadMusicaResponse
            {  // field description for DownloadMusicaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicaResponseDownloadMusicaResultLocalName, // DownloadMusicaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadMusicaResponse, DownloadMusicaResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for DownloadMusicaResult
            {  // fields description for _DownloadMusicaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMusicaResponsedescs.DownloadMusicaResult,
            },
        },    // _DownloadMusicaResponse
        {  // _DownloadTextura
            {  // field description for nome
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicanomeLocalName, // nome
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadTextura, nome),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for nome
            {  // fields description for _DownloadTextura
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadTexturadescs.nome,
            },
        },    // _DownloadTextura
        {  // _DownloadTexturaResponse
            {  // field description for DownloadTexturaResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadTexturaResponseDownloadTexturaResultLocalName, // DownloadTexturaResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadTexturaResponse, DownloadTexturaResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for DownloadTexturaResult
            {  // fields description for _DownloadTexturaResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadTexturaResponsedescs.DownloadTexturaResult,
            },
        },    // _DownloadTexturaResponse
        {  // _DownloadModeloInimigo
            {  // field description for nome
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicanomeLocalName, // nome
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadModeloInimigo, nome),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for nome
            {  // fields description for _DownloadModeloInimigo
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadModeloInimigodescs.nome,
            },
        },    // _DownloadModeloInimigo
        {  // _DownloadModeloInimigoResponse
            {  // field description for DownloadModeloInimigoResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadModeloInimigoResponseDownloadModeloInimigoResultLocalName, // DownloadModeloInimigoResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_DownloadModeloInimigoResponse, DownloadModeloInimigoResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for DownloadModeloInimigoResult
            {  // fields description for _DownloadModeloInimigoResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadModeloInimigoResponsedescs.DownloadModeloInimigoResult,
            },
        },    // _DownloadModeloInimigoResponse
    }, // end of global elements
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("InsertUploadData",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("user",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("score",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("mapa",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("InsertUploadDataResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("InsertUploadDataResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("CheckLogin",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("password",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("CheckLoginResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("CheckLoginResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("RegisterUser",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("RegisterUserResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("RegisterUserResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadMapa",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("fileName",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadMapaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadMapaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("GetNumberOfUsers",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("GetNumberOfUsersResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("GetNumberOfUsersResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("InsertTrack",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("map",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("track",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("InsertTrackResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("InsertTrackResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("InfoMapa",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("InfoMapaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("InfoMapaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 28),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadMusica",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 29),
            WS_XML_STRING_DICTIONARY_VALUE("nome",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 30),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadMusicaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 31),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadMusicaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 32),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadTextura",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 33),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadTexturaResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 34),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadTexturaResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 35),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadModeloInimigo",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 36),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadModeloInimigoResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 37),
            WS_XML_STRING_DICTIONARY_VALUE("DownloadModeloInimigoResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 38),
        },  // end of xmlStrings
        
        {  // tempuri_org_xsddictionary
          // 6b42245d-6d7e-4327-9a0c-d1df758fe402 
        { 0x6b42245d, 0x6d7e, 0x4327, { 0x9a, 0x0c, 0xd1,0xdf, 0x75, 0x8f, 0xe4, 0x02 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        39,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeName, // InsertUploadData
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.InsertUploadData,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataResponseTypeName, // InsertUploadDataResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.InsertUploadDataResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginTypeName, // CheckLogin
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.CheckLogin,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginResponseTypeName, // CheckLoginResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.CheckLoginResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._RegisterUserTypeName, // RegisterUser
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.RegisterUser,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._RegisterUserResponseTypeName, // RegisterUserResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.RegisterUserResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMapaTypeName, // DownloadMapa
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadMapa,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMapaResponseTypeName, // DownloadMapaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadMapaResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetNumberOfUsersTypeName, // GetNumberOfUsers
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetNumberOfUsers,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetNumberOfUsersResponseTypeName, // GetNumberOfUsersResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetNumberOfUsersResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTrackTypeName, // InsertTrack
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.InsertTrack,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTrackResponseTypeName, // InsertTrackResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.InsertTrackResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InfoMapaTypeName, // InfoMapa
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.InfoMapa,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InfoMapaResponseTypeName, // InfoMapaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.InfoMapaResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicaTypeName, // DownloadMusica
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadMusica,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicaResponseTypeName, // DownloadMusicaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadMusicaResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadTexturaTypeName, // DownloadTextura
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadTextura,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadTexturaResponseTypeName, // DownloadTexturaResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadTexturaResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadModeloInimigoTypeName, // DownloadModeloInimigo
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadModeloInimigo,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadModeloInimigoResponseTypeName, // DownloadModeloInimigoResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DownloadModeloInimigoResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_InsertUploadData),
        __alignof(_InsertUploadData),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDatadescs._InsertUploadDataFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDatadescs._InsertUploadDataFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeName, // InsertUploadData
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _InsertUploadData
        {
        sizeof(_InsertUploadDataResponse),
        __alignof(_InsertUploadDataResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDataResponsedescs._InsertUploadDataResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._InsertUploadDataResponsedescs._InsertUploadDataResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataResponseTypeName, // InsertUploadDataResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _InsertUploadDataResponse
        {
        sizeof(_CheckLogin),
        __alignof(_CheckLogin),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._CheckLogindescs._CheckLoginFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._CheckLogindescs._CheckLoginFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginTypeName, // CheckLogin
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _CheckLogin
        {
        sizeof(_CheckLoginResponse),
        __alignof(_CheckLoginResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._CheckLoginResponsedescs._CheckLoginResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._CheckLoginResponsedescs._CheckLoginResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._CheckLoginResponseTypeName, // CheckLoginResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _CheckLoginResponse
        {
        sizeof(_RegisterUser),
        __alignof(_RegisterUser),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserdescs._RegisterUserFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserdescs._RegisterUserFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._RegisterUserTypeName, // RegisterUser
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _RegisterUser
        {
        sizeof(_RegisterUserResponse),
        __alignof(_RegisterUserResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserResponsedescs._RegisterUserResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._RegisterUserResponsedescs._RegisterUserResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._RegisterUserResponseTypeName, // RegisterUserResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _RegisterUserResponse
        {
        sizeof(_DownloadMapa),
        __alignof(_DownloadMapa),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMapadescs._DownloadMapaFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadMapadescs._DownloadMapaFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMapaTypeName, // DownloadMapa
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadMapa
        {
        sizeof(_DownloadMapaResponse),
        __alignof(_DownloadMapaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMapaResponsedescs._DownloadMapaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadMapaResponsedescs._DownloadMapaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMapaResponseTypeName, // DownloadMapaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadMapaResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetNumberOfUsersTypeName, // GetNumberOfUsers
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetNumberOfUsers
        {
        sizeof(_GetNumberOfUsersResponse),
        __alignof(_GetNumberOfUsersResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetNumberOfUsersResponsedescs._GetNumberOfUsersResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetNumberOfUsersResponsedescs._GetNumberOfUsersResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetNumberOfUsersResponseTypeName, // GetNumberOfUsersResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetNumberOfUsersResponse
        {
        sizeof(_InsertTrack),
        __alignof(_InsertTrack),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackdescs._InsertTrackFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackdescs._InsertTrackFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTrackTypeName, // InsertTrack
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _InsertTrack
        {
        sizeof(_InsertTrackResponse),
        __alignof(_InsertTrackResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackResponsedescs._InsertTrackResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._InsertTrackResponsedescs._InsertTrackResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertTrackResponseTypeName, // InsertTrackResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _InsertTrackResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InfoMapaTypeName, // InfoMapa
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _InfoMapa
        {
        sizeof(_InfoMapaResponse),
        __alignof(_InfoMapaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._InfoMapaResponsedescs._InfoMapaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._InfoMapaResponsedescs._InfoMapaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InfoMapaResponseTypeName, // InfoMapaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _InfoMapaResponse
        {
        sizeof(_DownloadMusica),
        __alignof(_DownloadMusica),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMusicadescs._DownloadMusicaFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadMusicadescs._DownloadMusicaFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicaTypeName, // DownloadMusica
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadMusica
        {
        sizeof(_DownloadMusicaResponse),
        __alignof(_DownloadMusicaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadMusicaResponsedescs._DownloadMusicaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadMusicaResponsedescs._DownloadMusicaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadMusicaResponseTypeName, // DownloadMusicaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadMusicaResponse
        {
        sizeof(_DownloadTextura),
        __alignof(_DownloadTextura),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadTexturadescs._DownloadTexturaFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadTexturadescs._DownloadTexturaFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadTexturaTypeName, // DownloadTextura
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadTextura
        {
        sizeof(_DownloadTexturaResponse),
        __alignof(_DownloadTexturaResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadTexturaResponsedescs._DownloadTexturaResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadTexturaResponsedescs._DownloadTexturaResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadTexturaResponseTypeName, // DownloadTexturaResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadTexturaResponse
        {
        sizeof(_DownloadModeloInimigo),
        __alignof(_DownloadModeloInimigo),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadModeloInimigodescs._DownloadModeloInimigoFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadModeloInimigodescs._DownloadModeloInimigoFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadModeloInimigoTypeName, // DownloadModeloInimigo
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadModeloInimigo
        {
        sizeof(_DownloadModeloInimigoResponse),
        __alignof(_DownloadModeloInimigoResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._DownloadModeloInimigoResponsedescs._DownloadModeloInimigoResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._DownloadModeloInimigoResponsedescs._DownloadModeloInimigoResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DownloadModeloInimigoResponseTypeName, // DownloadModeloInimigoResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._InsertUploadDataTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DownloadModeloInimigoResponse
    },  // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
