
// File generated by Wsutil Compiler version 1.0095 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by Wsutil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _InsertUploadData;
//     struct _InsertUploadDataResponse;
//     struct _CheckLogin;
//     struct _CheckLoginResponse;
//     struct _RegisterUser;
//     struct _RegisterUserResponse;
//     struct _DownloadMapa;
//     struct _DownloadMapaResponse;
//     struct _GetNumberOfUsers;
//     struct _GetNumberOfUsersResponse;
//     struct _InsertTrack;
//     struct _InsertTrackResponse;
//     struct _InfoMapa;
//     struct _InfoMapaResponse;
//     struct _DownloadMusica;
//     struct _DownloadMusicaResponse;
//     struct _DownloadTextura;
//     struct _DownloadTexturaResponse;
//     struct _DownloadModeloInimigo;
//     struct _DownloadModeloInimigoResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: n/a
typedef struct _InsertUploadData 
{
    WCHAR* user; // optional
    int score;
    WCHAR* mapa; // optional
} _InsertUploadData;

// typeDescription: n/a
typedef struct _InsertUploadDataResponse 
{
    BOOL InsertUploadDataResult;
} _InsertUploadDataResponse;

// typeDescription: n/a
typedef struct _CheckLogin 
{
    WCHAR* user; // optional
    WCHAR* password; // optional
} _CheckLogin;

// typeDescription: n/a
typedef struct _CheckLoginResponse 
{
    BOOL CheckLoginResult;
} _CheckLoginResponse;

// typeDescription: n/a
typedef struct _RegisterUser 
{
    WCHAR* user; // optional
    WCHAR* password; // optional
} _RegisterUser;

// typeDescription: n/a
typedef struct _RegisterUserResponse 
{
    BOOL RegisterUserResult;
} _RegisterUserResponse;

// typeDescription: n/a
typedef struct _DownloadMapa 
{
    WCHAR* fileName; // optional
} _DownloadMapa;

// typeDescription: n/a
typedef struct _DownloadMapaResponse 
{
    WCHAR* DownloadMapaResult; // optional
} _DownloadMapaResponse;

typedef struct _GetNumberOfUsers _GetNumberOfUsers;

// typeDescription: n/a
typedef struct _GetNumberOfUsersResponse 
{
    int GetNumberOfUsersResult;
} _GetNumberOfUsersResponse;

// typeDescription: n/a
typedef struct _InsertTrack 
{
    WCHAR* user; // optional
    WCHAR* map; // optional
    WCHAR* track; // optional
} _InsertTrack;

// typeDescription: n/a
typedef struct _InsertTrackResponse 
{
    BOOL InsertTrackResult;
} _InsertTrackResponse;

typedef struct _InfoMapa _InfoMapa;

// typeDescription: n/a
typedef struct _InfoMapaResponse 
{
    WCHAR* InfoMapaResult; // optional
} _InfoMapaResponse;

// typeDescription: n/a
typedef struct _DownloadMusica 
{
    WCHAR* nome; // optional
} _DownloadMusica;

// typeDescription: n/a
typedef struct _DownloadMusicaResponse 
{
    WCHAR* DownloadMusicaResult; // optional
} _DownloadMusicaResponse;

// typeDescription: n/a
typedef struct _DownloadTextura 
{
    WCHAR* nome; // optional
} _DownloadTextura;

// typeDescription: n/a
typedef struct _DownloadTexturaResponse 
{
    WCHAR* DownloadTexturaResult; // optional
} _DownloadTexturaResponse;

// typeDescription: n/a
typedef struct _DownloadModeloInimigo 
{
    WCHAR* nome; // optional
} _DownloadModeloInimigo;

// typeDescription: n/a
typedef struct _DownloadModeloInimigoResponse 
{
    WCHAR* DownloadModeloInimigoResult; // optional
} _DownloadModeloInimigoResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: InsertUploadData ("http://tempuri.org/")
        // c type: _InsertUploadData
        // elementDescription: tempuri_org_xsd.globalElements.InsertUploadData
        WS_ELEMENT_DESCRIPTION InsertUploadData;
        
        // xml element: InsertUploadDataResponse ("http://tempuri.org/")
        // c type: _InsertUploadDataResponse
        // elementDescription: tempuri_org_xsd.globalElements.InsertUploadDataResponse
        WS_ELEMENT_DESCRIPTION InsertUploadDataResponse;
        
        // xml element: CheckLogin ("http://tempuri.org/")
        // c type: _CheckLogin
        // elementDescription: tempuri_org_xsd.globalElements.CheckLogin
        WS_ELEMENT_DESCRIPTION CheckLogin;
        
        // xml element: CheckLoginResponse ("http://tempuri.org/")
        // c type: _CheckLoginResponse
        // elementDescription: tempuri_org_xsd.globalElements.CheckLoginResponse
        WS_ELEMENT_DESCRIPTION CheckLoginResponse;
        
        // xml element: RegisterUser ("http://tempuri.org/")
        // c type: _RegisterUser
        // elementDescription: tempuri_org_xsd.globalElements.RegisterUser
        WS_ELEMENT_DESCRIPTION RegisterUser;
        
        // xml element: RegisterUserResponse ("http://tempuri.org/")
        // c type: _RegisterUserResponse
        // elementDescription: tempuri_org_xsd.globalElements.RegisterUserResponse
        WS_ELEMENT_DESCRIPTION RegisterUserResponse;
        
        // xml element: DownloadMapa ("http://tempuri.org/")
        // c type: _DownloadMapa
        // elementDescription: tempuri_org_xsd.globalElements.DownloadMapa
        WS_ELEMENT_DESCRIPTION DownloadMapa;
        
        // xml element: DownloadMapaResponse ("http://tempuri.org/")
        // c type: _DownloadMapaResponse
        // elementDescription: tempuri_org_xsd.globalElements.DownloadMapaResponse
        WS_ELEMENT_DESCRIPTION DownloadMapaResponse;
        
        // xml element: GetNumberOfUsers ("http://tempuri.org/")
        // c type: _GetNumberOfUsers
        // elementDescription: tempuri_org_xsd.globalElements.GetNumberOfUsers
        WS_ELEMENT_DESCRIPTION GetNumberOfUsers;
        
        // xml element: GetNumberOfUsersResponse ("http://tempuri.org/")
        // c type: _GetNumberOfUsersResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetNumberOfUsersResponse
        WS_ELEMENT_DESCRIPTION GetNumberOfUsersResponse;
        
        // xml element: InsertTrack ("http://tempuri.org/")
        // c type: _InsertTrack
        // elementDescription: tempuri_org_xsd.globalElements.InsertTrack
        WS_ELEMENT_DESCRIPTION InsertTrack;
        
        // xml element: InsertTrackResponse ("http://tempuri.org/")
        // c type: _InsertTrackResponse
        // elementDescription: tempuri_org_xsd.globalElements.InsertTrackResponse
        WS_ELEMENT_DESCRIPTION InsertTrackResponse;
        
        // xml element: InfoMapa ("http://tempuri.org/")
        // c type: _InfoMapa
        // elementDescription: tempuri_org_xsd.globalElements.InfoMapa
        WS_ELEMENT_DESCRIPTION InfoMapa;
        
        // xml element: InfoMapaResponse ("http://tempuri.org/")
        // c type: _InfoMapaResponse
        // elementDescription: tempuri_org_xsd.globalElements.InfoMapaResponse
        WS_ELEMENT_DESCRIPTION InfoMapaResponse;
        
        // xml element: DownloadMusica ("http://tempuri.org/")
        // c type: _DownloadMusica
        // elementDescription: tempuri_org_xsd.globalElements.DownloadMusica
        WS_ELEMENT_DESCRIPTION DownloadMusica;
        
        // xml element: DownloadMusicaResponse ("http://tempuri.org/")
        // c type: _DownloadMusicaResponse
        // elementDescription: tempuri_org_xsd.globalElements.DownloadMusicaResponse
        WS_ELEMENT_DESCRIPTION DownloadMusicaResponse;
        
        // xml element: DownloadTextura ("http://tempuri.org/")
        // c type: _DownloadTextura
        // elementDescription: tempuri_org_xsd.globalElements.DownloadTextura
        WS_ELEMENT_DESCRIPTION DownloadTextura;
        
        // xml element: DownloadTexturaResponse ("http://tempuri.org/")
        // c type: _DownloadTexturaResponse
        // elementDescription: tempuri_org_xsd.globalElements.DownloadTexturaResponse
        WS_ELEMENT_DESCRIPTION DownloadTexturaResponse;
        
        // xml element: DownloadModeloInimigo ("http://tempuri.org/")
        // c type: _DownloadModeloInimigo
        // elementDescription: tempuri_org_xsd.globalElements.DownloadModeloInimigo
        WS_ELEMENT_DESCRIPTION DownloadModeloInimigo;
        
        // xml element: DownloadModeloInimigoResponse ("http://tempuri.org/")
        // c type: _DownloadModeloInimigoResponse
        // elementDescription: tempuri_org_xsd.globalElements.DownloadModeloInimigoResponse
        WS_ELEMENT_DESCRIPTION DownloadModeloInimigoResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION InsertUploadData;
        WS_STRUCT_DESCRIPTION InsertUploadDataResponse;
        WS_STRUCT_DESCRIPTION CheckLogin;
        WS_STRUCT_DESCRIPTION CheckLoginResponse;
        WS_STRUCT_DESCRIPTION RegisterUser;
        WS_STRUCT_DESCRIPTION RegisterUserResponse;
        WS_STRUCT_DESCRIPTION DownloadMapa;
        WS_STRUCT_DESCRIPTION DownloadMapaResponse;
        WS_STRUCT_DESCRIPTION GetNumberOfUsers;
        WS_STRUCT_DESCRIPTION GetNumberOfUsersResponse;
        WS_STRUCT_DESCRIPTION InsertTrack;
        WS_STRUCT_DESCRIPTION InsertTrackResponse;
        WS_STRUCT_DESCRIPTION InfoMapa;
        WS_STRUCT_DESCRIPTION InfoMapaResponse;
        WS_STRUCT_DESCRIPTION DownloadMusica;
        WS_STRUCT_DESCRIPTION DownloadMusicaResponse;
        WS_STRUCT_DESCRIPTION DownloadTextura;
        WS_STRUCT_DESCRIPTION DownloadTexturaResponse;
        WS_STRUCT_DESCRIPTION DownloadModeloInimigo;
        WS_STRUCT_DESCRIPTION DownloadModeloInimigoResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

